stages:
  - build
  - deploy_test
  - deploy_prod

variables:
  TEST_USER: user
  PROD_USER: user
  TEST_SERVER: "192.168.105.35"
  PROD_SERVER: "192.168.105.3"

building image:
  stage: build
  script:
    - echo "Building docker image"
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker rmi ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell

testing image:
  stage: deploy_test
  when: on_success
  script:
    - echo "Deploying to testing server"
    - ssh ${TEST_USER}@${TEST_SERVER} "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}"
    - ssh ${TEST_USER}@${TEST_SERVER} "docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - ssh ${TEST_USER}@${TEST_SERVER} "docker rm --force poller_testing || true"
    - ssh ${TEST_USER}@${TEST_SERVER} "docker run --rm --name poller_testing -d -p 8899:8899 ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - sleep 5
    - telnet ${TEST_SERVER} 8899 | grep -q "Connected"
    - echo $?
  after_script:
    - ssh ${TEST_USER}@${TEST_SERVER} "docker rm --force poller_testing || true"
    - ssh ${TEST_USER}@${TEST_SERVER} "docker rmi ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  tags:
    - shell

deploying on prod:
  stage: deploy_prod
  when: on_success
  script:
    - echo "Deploying service to production server"
    - ssh ${PROD_USER}@${PROD_SERVER} "docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}"
    - ssh ${PROD_USER}@${PROD_SERVER} "docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - ssh ${PROD_USER}@${PROD_SERVER} "docker rm --force poller || true"
    - ssh ${PROD_USER}@${PROD_SERVER} "docker run --name poller -d --restart always -p 8899:8899 ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  tags:
    - shell
